image: node:14.17.4

stages:
  - build
  - deploy

Build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist

Pages:
  stage: deploy
  tags:
    - pages
  script:
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
